# Generated by Django 4.2.4 on 2023-08-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_updated',
            new_name='updated_at',
        ),
    ]
